### ISSUE TITLE
Packet Detected but not classified

### ISSUE THREAD

**Issue by ahuseinnf** [benzi96/snort3-plugin-ML#7]
![image](https://user-images.githubusercontent.com/58802002/167756384-3b3d1d51-fcc9-42f5-99e6-844d5f117d54.png)

My plugin have successfully detected the traffic packets, but not classified as anomalies or normal packets, just total packets showing up... this is the backtrace on my terminal.
`/root/snort3-plugin-ML/AnalysisServer/env/lib/python3.6/site-packages/sklearn/preprocessing/_data.py:373: RuntimeWarning: All-NaN slice encountered
  data_min = np.nanmin(X, axis=0)
/root/snort3-plugin-ML/AnalysisServer/env/lib/python3.6/site-packages/sklearn/preprocessing/_data.py:374: RuntimeWarning: All-NaN slice encountered
  data_max = np.nanmax(X, axis=0)
Traceback (most recent call last):
  File "/root/snort3-plugin-ML/AnalysisServer/env/lib/python3.6/site-packages/gevent/pywsgi.py", line 999, in handle_one_response
    self.run_application()
  File "/root/snort3-plugin-ML/AnalysisServer/env/lib/python3.6/site-packages/geventwebsocket/handler.py", line 75, in run_application
    self.run_websocket()
  File "/root/snort3-plugin-ML/AnalysisServer/env/lib/python3.6/site-packages/geventwebsocket/handler.py", line 52, in run_websocket
    list(self.application(self.environ, lambda s, h, e=None: []))
  File "/root/snort3-plugin-ML/AnalysisServer/env/lib/python3.6/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/snort3-plugin-ML/AnalysisServer/env/lib/python3.6/site-packages/flask_sockets.py", line 45, in __call__
    handler(environment, **values)
  File "main.py", line 65, in web_socket
    data = svm.predict(listPackets)
  File "/root/snort3-plugin-ML/AnalysisServer/MachineLearningAlgorithm/svm.py", line 67, in predict
    predict = self.clf.predict(data)
  File "/root/snort3-plugin-ML/AnalysisServer/env/lib/python3.6/site-packages/sklearn/linear_model/_base.py", line 307, in predict
    scores = self.decision_function(X)
  File "/root/snort3-plugin-ML/AnalysisServer/env/lib/python3.6/site-packages/sklearn/linear_model/_base.py", line 282, in decision_function
    X = check_array(X, accept_sparse='csr')
  File "/root/snort3-plugin-ML/AnalysisServer/env/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/root/snort3-plugin-ML/AnalysisServer/env/lib/python3.6/site-packages/sklearn/utils/validation.py", line 646, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/root/snort3-plugin-ML/AnalysisServer/env/lib/python3.6/site-packages/sklearn/utils/validation.py", line 100, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
2022-05-11T02:24:27Z {'REMOTE_ADDR': '::ffff:192.168.56.1', 'REMOTE_PORT': '56679', 'HTTP_HOST': '192.168.56.101:5000', (hidden keys: 31)} failed with ValueError
`

help please thank you

**Comment by benzi96** [comment]
Please use 28 features instead of full features of KDD.
I have updated the main.py to use only 28 features.

![image](https://user-images.githubusercontent.com/32060434/168605260-89162448-533a-41fd-8c4b-4e9aa30c88f8.png)

**Comment by ahuseinnf** [comment]
> Please use 28 features instead of full features of KDD. I have updated the main.py to use only 28 features.
> 
> ![image](https://user-images.githubusercontent.com/32060434/168605260-89162448-533a-41fd-8c4b-4e9aa30c88f8.png)

it works thanks
